/* @flow */
const fs = require('fs')
const path = require('path')
const { execFileSync } = require('child_process')
const flow = require('flow-bin')
const parser = require('flow-parser-bin')
const debug = obj => console.log(JSON.stringify(obj, null, 2))

function getTypeAtPos(fpath: string, line: number, column: number) {
  const ret = execFileSync(flow, [
    'type-at-pos',
    fpath,
    `${line}`,
    `${column}`,
    '--json'
  ]).toString()
  return JSON.parse(ret)
}

function getExportDefaultType(fpath: string): string | null {
  const body = fs.readFileSync(fpath).toString()
  const ast = parser.parse(body)
  const exportDefaultNode = ast.body.find(
    node => node.type === 'ExportDefaultDeclaration'
  )

  if (exportDefaultNode) {
    const start = exportDefaultNode.declaration.loc.start
    const { type } = getTypeAtPos(fpath, start.line, start.column + 1)
    return type
  }
  return null
}

function astToObject(node) {
  switch (node.type) {
    case 'ObjectTypeAnnotation': {
      return node.properties.reduce((acc, property) => {
        // TODO: Check key is optional
        return { ...acc, [property.key.name]: astToObject(property.value) }
      }, {})
    }
    case 'GenericTypeAnnotation': {
      if (node.id.name === 'Array') {
        return [astToObject(node.typeParameters.params[0])]
      } else {
        // TODO: Trace type instance
        return null
      }
    }
    case 'NumberTypeAnnotation': {
      return 42
    }
    case 'StringTypeAnnotation': {
      return '<string>'
    }
    case 'AnyTypeAnnotation': {
      return '<any>'
    }
    default: {
      console.error('missing:', node.type)
      return null
    }
  }
}

const header = `/* @flow */
import React from 'react'
import { storiesOf } from '@storybook/react'
const ctx = storiesOf('Generated by flow', module)
`
const template = (fpath: string, props: any) => `${header}
import App from '../../src/components/App'
ctx.add('${fpath}', () => <App {...${JSON.stringify(props)}}/>)
`

const targetPath = path.join(__dirname, '../src/components/App.js')
const typeExprString = getExportDefaultType(targetPath)
if (typeExprString) {
  const typeExpr = parser.parse('type T = ' + typeExprString).body[0].right
  // debug(astToObject(typeExpr.params[0].typeAnnotation))
  const props = astToObject(typeExpr.params[0].typeAnnotation)
  const ret = template(targetPath, props)
  console.log(ret) // write file to .storybook/.gen
}
