/* @flow */
import React from 'react'
import { storiesOf } from '@storybook/react'
const ctx = storiesOf('Generated by flow', module)
import C from '../../src/components/App.js'
ctx.add('../../src/components/App.js', () => <C {...{"a":"<string>","arr":[42],"c":{"d":{"e":"<any>"}},"p":{"x":42,"y":42}}}/>)
