/* @flow */
import React from 'react'
import { storiesOf } from '@storybook/react'
const ctx = storiesOf('Generated by flow', module)
import C from '../../src/components/App.js'
ctx.add('../../src/components/App.js', () => <C {...{"a":"<string: props.a>","arr":[42],"c":{"d":{"e":"<any: props.c.d.e>"}},"objArr":[{"v":"<string: props.objArr.*.v>"}],"p":{"x":42,"y":42}}}/>)
