/* @flow */
import React from 'react'
import { storiesOf } from '@storybook/react'
const ctx = storiesOf('Generated by flow', module)
import C from '../../src/components/nested/Nested.js'
ctx.add('../../src/components/nested/Nested.js', () => <C {...{}}/>)
