/* @flow */
import React from 'react'
import { storiesOf } from '@storybook/react'
const ctx = storiesOf('Generated by flow', module)

import App from '../../src/components/App'
ctx.add('/Users/mz/sandbox/flowstory/src/components/App.js', () => <App {...{"a":"<string>","arr":[42],"c":{"d":{"e":"<any>"}},"p":{"x":42,"y":42}}}/>)

